name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build jar
        run: ./gradlew test assemble shadowJar
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: All Tests
          path: warden-roboto/build/test-results/**/TEST*.xml
          reporter: java-junit
      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: warden-roboto
          path: |
            warden-roboto/build/libs/*jar
            attestation-diag/build/libs/attestation-diag-*-all.jar